log:
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :80

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: mass-payments-sender-svc
  service_port: 80
